### ISSUE TITLE
프론트 - 작품 리스트 페이지 만들기

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#10]
## 개요
작품 리스트 페이지 만들기

**Comment by nablyy** [comment]
[#22](https://github.com/yamujine/artmatch/issues/22) 준호님 장소 리스트를 많이 참고했습니다.
![작품목록](http://postfiles8.naver.net/MjAxNzAyMTBfMTg0/MDAxNDg2NzEyOTgxNzc2.NfyYhwcklAMQRbi2TgL_Yw-NjnzWvfI7hTXcPg4lPHUg.EVYqgtVlvCt5FubzWSEhpcwLTKI22485xRHiSofDng4g.PNG.gongsuni94/%EC%BA%A1%EC%B2%98.PNG?type=w773)

**Comment by nablyy** [comment]
남우님 리뷰 적용

**Comment by junho85** [comment]
다 했으면 close 해 주세요~
