### ISSUE TITLE
pick 모델 분리

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#111]
- [x] 모델 분리
- [x] 서비스 로직 분리 (model -> controller)

**Comment by junho85** [comment]
참고: https://github.com/yamujine/artmatch/issues/112

기존 모델
Pick_model.php

Artwork_Pick_model.php
Place_Pick_model.php
로 분리

my_models.php

Artwork_Pick_model.php 작업

* [ ] pick_model 제거
