### ISSUE TITLE
comment 모델 분리

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#112]
- [x] 모델 분리
- [x] 서비스 로직 분리 (model -> controller)

**Comment by junho85** [comment]
서비스 로직은 남우님이 했다고 표시 했으니 모델분리만 하면 되겠지

**Comment by junho85** [comment]
Artwork_Comment_model.php
Place_Comment_model.php
파일 생성

Comment_model.php 는 deprecated 처리
