### ISSUE TITLE
서버 - 배포 유의사항

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#12]
배포시 환경 변수 export CI_ENV="production"
index.php line 56 참고

**Comment by kimtree** [comment]
https://github.com/yamujine/deploy-artmatch/commit/f120f33427dfecc49d6d62bf5c401db063382e78

**Comment by junho85** [comment]
@kimtree 
production, develop 구분을 하기 위함인가요?
배포 스크립트에서 서버를 재시작 하거나 배포 스크립트 내에서 환경변수를 사용할 일이 없으면 별로 의미는 없지 않나요?
웹서버 (아파치 or nginx) 설정이나 실행 스크립트에서 환경 변수를 지정해 주는게 더 확실할 것 같습니다.

**Comment by kimtree** [comment]
@junho85 환경 변수 되어 있으면 CI에서 prod/dev 설정을 각각 사용할 수 있어서(폴더별로 구분도 되고) 배포 스크립트에 환경 변수 설정 내용을 추가하긴 했는데, 웹서버 conf 단에서 변수 지정하면 저 부분은 없어도 될 것 같습니다! 
다만 나중에 새로 새버 세팅시 빼놓을 수 있으니 따로 문서화 시키면 좋을 것 같아요~

**Comment by kimtree** [comment]
nginx의 설정 파일에서 아래와 같이 설정하는 것으로 갈음.
fastcgi_param CI_ENV production;
