### ISSUE TITLE
Artworks:index, Places:index 정리

### ISSUE THREAD

**Issue by mintplo** [yamujine/artmatch#123]
Artworks:index -> list.twig
Places:index -> list.twig

과 같이 현재 사용하지 않고 앞으로도 사용하지 않을 Twig 파일 및 Controller route는 정리하면 좋을것 같습니다.

**Comment by kimtree** [comment]
https://github.com/yamujine/artmatch/commit/ee6464c266bdacb1dd09ae6a1f731140199df9ea 커밋에서 제거 처리 및 /artworks /places route 접속시 메인으로 리다이렉트 되도록 하였습니다.
