### ISSUE TITLE
장소 상세 내 희망 전시 리스트 표시

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#149]
- 현재 장소 등록시 전시 정보를 입력하게 되어 있음 ( 전시비 지급 관련, 기간, 원하는 작품 수 )
- 하지만, 현재 장소 상세 페이지에서는 장소 등록자가 원하는 전시 정보를 표시하는 내용이 없음

**Comment by thorlee** [comment]
이게 원래 목록에서 노출되는 정보였는데, 디자인에서 제거되었네요.
장소상세의 전시공간 정보와 전시되었던 작품 목록 사이에 추가되어야 할것 같습니다.
일단 상세 API에는 데이터를 내려주고, 디자인에 추가해서 진행하도록 하지요.

**Comment by kimtree** [comment]
일단 현재 진행 안하는 것으로 이슈 클로즈
