### ISSUE TITLE
서버 - 패키지 관리

### ISSUE THREAD

**Issue by mintplo** [yamujine/artmatch#15]
CI 관련 라이브러리 같은 경우에는 코드를 직접 받아서 3rd party 폴더에 둔 후 사용하지만

CI 라이브러리가 아닌 패키지는 어떻게 관리를 할 수 있을까요?

PHP 패키지 관리는 요새 Composer로 관리하긴 하지만 관련 라이브러리 코드를 직접 받아 사용하는 방법도

현재 상태에서도 문제는 없을것 같습니다만 다른 분들 생각은 어떠신가요?

**Comment by junho85** [comment]
Composer 로 할 수 있는건 Composer 로 하고 아닌건 직접 받아서 쓰면 될 거 같습니다. (뭔가 뻔한 답변 느낌;;)
