### ISSUE TITLE
장소 내 주소 표시 문제

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#150]
<img width="1063" alt="2017-02-21 01 03 59" src="https://cloud.githubusercontent.com/assets/557307/23132658/a5c28a10-f7d1-11e6-895a-1265647bdd69.png">

장소 상세 페이지 최상단에 "성신여대" 부분에 무엇이 들어가야 할까요?
입력 받는 값은 주소로 "경기도 성남시 분당구 판교역로 235 에이치스퀘어 N동 7층" 라는 값만 저장되어 있는 상태.

**Comment by thorlee** [comment]
대표장소가 추가되어여 겠네요.
장소는 2개를 직접 입력받습니다.
- 대표장소 
- 상세주소 
이렇게 추가하면 될것 같습니다.

**Comment by kimtree** [comment]
@thorlee 확인했습니다.
