### ISSUE TITLE
작품 상세 - 전시했던 장소 목록

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#159]
<img width="916" alt="2017-02-22 00 15 51" src="https://cloud.githubusercontent.com/assets/557307/23170883/29fade82-f894-11e6-9d24-42d7ca3539a1.png">

<img width="907" alt="2017-02-22 00 18 20" src="https://cloud.githubusercontent.com/assets/557307/23171044/b9bad0ea-f894-11e6-9e0f-0c148f6499cc.png">

장소 목록에서 시안에서는 2016.12.10 - 24 로 되어있는데, 전시 기간 중 달이 바뀌거나 연도가 바뀌면 어떻게 되는건가요? 일단 전체 연월일 표시하도록 변경했는데 이런 경우에는 키워드에 성신여대만 입력해도 UI가 깨집니다. 디자인 분들과 확인 부탁드립니다. (키워드가 조금이라도 길어지면 날짜가 밀리기 때문에 날짜 정보를 아래로 내려도 좋을 것 같습니다.)

**Comment by mintplo** [comment]
디자이너분들이 깃헙을 안쓰시기 때문에ㅠㅠ
