### ISSUE TITLE
서버 - 기획 초안에 따른 route 설정

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#16]
1. 메인 (작품/장소 탭으로 구분되는 목록 나오는 부분) -> /
2. 로그인 -> /login
3. 회원가입 -> /signup
4. 작품 상세 -> /artwork/999
5. 장소 상세 -> /place/191
6. 마이페이지 -> /mypage

**Comment by mintplo** [comment]
복수 형태로 표현할 수 있는 URI는 복수 형태로 표현하는 것이 더 나을것 같습니다.

/places/{place_id}
/artworks/{artwork_id}

마이 페이지 같은 경우에는 /me 어떨까요?

**Comment by junho85** [comment]
저도 복수 찬성합니다. RESTful api 작업 가이드 권장 사항.

마이 페이지는 혹시 개인 정보 설정 페이지인가요?
그렇다면 github 처럼 settings 로 가면 어떨까요? ex) https://github.com/settings/profile

혹시 링크드인처럼 유저정보와 유저가 올린 정보 볼 수 있는 페이지라면 /users/{user_id} 와 같은 형식이 좋을 듯 합니다. 
다만 소셜 로그인 하더라도 아이디는 하나 만들어야 된다는 번거로움은 생깁니다만 장기적으로 개인 포트폴리오 지원 한다면 필요할 듯 합니다.

**Comment by kimtree** [comment]
== 리뷰 코멘트는 https://github.com/yamujine/artmatch/pull/17 여기서만 해주세요. ==

**Comment by kimtree** [comment]
현재까지 결정된 사항

메인 (작품/장소 탭으로 구분되는 목록 나오는 부분) -> /
로그인 -> /login
회원가입 -> /signup
작품 상세 -> /artworks/<artwork_id>
장소 상세 -> /places/<place_id>
내 프로필 페이지 -> /users/me
회원 프로필 페이지 -> /users/<user_id>

**Comment by junho85** [comment]
https://github.com/yamujine/artmatch/wiki/route 에 결정된 사항 정리 하였습니다.
