### ISSUE TITLE
장소/작품 상세 전시 내용 표시 관련

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#160]
<img width="915" alt="2017-02-22 00 16 00" src="https://cloud.githubusercontent.com/assets/557307/23171086/dcd233f2-f894-11e6-8812-9add8f054920.png">

전시 내용이 4개 이상이 되는 경우에 아래와 같이 UI가 깨집니다. 오른쪽 위 01/02 구분은 페이징인 것인가요?
페이징이 도입되면 개발 & 프론트 공수가 늘어나기 때문에 슬라이더 등으로 해결하거나 최근 n개를 보여주는 식이면 좋을 것 같습니다.

**Comment by mintplo** [comment]
이 부분은 실제로 서버 연동 코드가 입혀지면 작업하려 했는데 TODO 처리를 까먹고 안했나 봅니다.

이와는 별개로 페이징인지 단순히 8개만 불러와서 2페이지 페이징인지는 별도 확인후 코멘트하겠습니다!

**Comment by mintplo** [comment]
전체 페이징을 원하시는데 개발 공수 때문에 일단 최대 8개 불러와서 Carousel로 구현하는게 좋을것 같습니다.
