### ISSUE TITLE
장소 상세에서 해당 장소 소유자의 다른 장소 보기

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#162]
현재 장소 상세에서는 해당 장소 소유자의 기타 등록된 장소를 보는 페이지로 넘어가는 기능이 없음
장소 소유자가 여러 장소를 등록할 수 있고, 이 장소들을 마이페이지에서 확인 가능하기 때문에 장소 상세페이지에서 해당 장소 소유자의 공개 마이페이지를 접속할 방법이 있어야 할 것 같습니다.

**Comment by thorlee** [comment]
장소등록자의 프로필사진이 나오는 곳에 ID도 같이 노출하고 해당 부분을 클릭하면 이동하면 괜찮을것 같습니다.

**Comment by kimtree** [comment]
대표의 한마디 -> 유저 아이디 표시하도록 결정

**Comment by kimtree** [comment]
@mintplo 여기도 마찬가지로 https://github.com/yamujine/artmatch/commit/c4641341a55ee0de9acbdfab19c8dbd803d897c2 커밋에서 "XX의 한마디"의 XX 자리에 유저 아이디 표시 및 링크 걸었습니다. 확인 후 이상 없으면 close 해주세요.
