### ISSUE TITLE
작품 상세에서 해당 작가의 다른 작품 보기

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#163]
현재 작품 상세에서 해당 작가의 마이페이지를 보는 기능이 없음

- 작품 제목 바로 아래 또는 copyright 부분 작가 이름을 클릭시 넘어가야할지?
- 작품 상세 내에서 작가의 다른 작품들도 보여주는 섹션이 추가되면 좋을지?

**Comment by thorlee** [comment]
- copyright 부분에는 노출되지 않아도 될 것 같고, 장소쪽과 맞추어서 작품 등록자의 프로필사진이 나오는 곳에 ID도 같이 노출하고 해당 부분을 클릭하면 이동하면 괜찮을것 같습니다.
- 작품 상세 내에서 작가의 다른 작품을 횡스크롤로 보여주는 섹션도 있으면 좋을 것 같네요. 이건 기존 프로세스 완성되고 추가 작업되면 좋을 것 같습니다.

**Comment by kimtree** [comment]
작가의 한마디 -> 작가 아이디 표시하도록 변경

**Comment by kimtree** [comment]
@mintplo https://github.com/yamujine/artmatch/commit/c4641341a55ee0de9acbdfab19c8dbd803d897c2 커밋에서 "XX의 한마디"의 XX 자리에 유저 아이디 표시 및 링크 걸었습니다. 확인 후 이상 없으면 close 해주세요.
