### ISSUE TITLE
작품 상세 페이지 전시 기간 관련

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#165]
<img width="689" alt="2017-02-22 01 20 10" src="https://cloud.githubusercontent.com/assets/557307/23173626/1f783190-f89d-11e6-93e5-2448695d5b96.png">

작품 상세에서 "() ~ () 까지 n개 작품 전시중" 이라는 멘트가 있음
- 해당 작품 1개는 1곳의 전시에만 전시되는데 n개의 작품 전시중은 올바르지 않은 표기
- 만약 작가의 모든 작품에 대한 정보라면 여러개 전시를 진행중인 경우 날짜를 합산해서 전체 범위 + 전시 작품 갯수 카운트까지 계산해 주어야 하는지?

장소도 동일한 로직이 있지만 현재 장소는 1개의 전시만을 허용하고 있는 구조이기 때문에 정보 표시에 지장 X

**Comment by thorlee** [comment]
기획에서 없던 문구가 추가되어 있네요. 해당 부분은 디자인에서 잡은 문구 인것 같은데,
전시중일 경우에는 n개의 작품 전시중이라는 문구는 제외하고 전시 기간만 노출하면 됩니다.

**Comment by kimtree** [comment]
@thorlee 여기는 작품 상세 페이지인데요, 해당 작가가 진행중인 모든 전시를 찾아서 전시기간을 합산해서 보여주는 방식을 말씀하시는 것 인가요?

**Comment by thorlee** [comment]
아 -_-;; 작품상세 페이지네요.. 
착가했군요;;
이건 아예 없던 feature가 들어간건데. 그냥 일단은 제외하고 캠프때 여력이 되면 추가하는걸로 하는게 좋겠습니다.

**Comment by kimtree** [comment]
https://github.com/yamujine/artmatch/commit/7d79e45d9c457445b4c842eea2ae7450fc6666c2 커밋에서 임시 제거하였습니다.
