### ISSUE TITLE
작품/장소 댓글 - 이름 자리에는 user_name이 표시되도록

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#168]
지금 user_id 가 나오고 있음. 유저 테이블에서 이름 가져와야 됨.
![image](https://cloud.githubusercontent.com/assets/1219373/23193240/39e42950-f8eb-11e6-930e-ee76bc214a8e.png)

**Comment by kimtree** [comment]
이름 정보는 현재 저장하고 있지 않는데... 흠 이것도 난감하네요.

**Comment by kimtree** [comment]
@thorlee 현재 기획안 상에서 전부 유저 ID가 표시되는 로직으로 되어있고, 그에 따라서 개발이 되었습니다. 이름 또는 작가명 관련 필드 추가에 대해서 의견 부탁드립니다. (디자인 시안 상에서는 이름으로 보이는 것들로 시안이 되어 있기는 합니다.)

**Comment by thorlee** [comment]
id로 저장되는게 맞아 보입니다.
오히려 상세에서 이름만 노출되는 경우에는 id도 같이 보여줘야 할 것 같아요.
나중에 @ id 기능으로 댓글을 달 수도 있을텐데... id를 모르면 안될것 같네요~

**Comment by kimtree** [comment]
@thorlee 현재 따로 닉네임 필드가 없는데 그럼 서비스 전역에서 사용하는 "이름" 정보는 유저ID가 표시되면 되는 걸까요?

**Comment by junho85** [comment]
제 생각에도 그냥 users 테이블의 user_name 정보 (ex junho85) 가 나오면 되지 않을까 싶습니다.

**Comment by nablyy** [comment]
id 정보는 가지고만 있고 user_name 을 노출하면 되지 않을까요?
일단 현 상황에서는 user_name 정보를 노출시키는 것이 제일 깔끔할 것 같긴합니다.

**Comment by nablyy** [comment]
지금 하고 있는데 user 테이블 에서 user_name 정보 가져와서 보여주는 방식으로 짜겠습니다.
수정사항 생길 경우 이후 개선하면 될 것 같아요.

**Comment by thorlee** [comment]
그럼 users 테이블에서 user_name 을 조회해서 사용하는 것으로 진행하신다고 하니~
반대는 하지 않겠습니다 ^^
중요한건 아니어서 개발이 편한쪽으로 하자는게 의견이었습니다~

**Comment by kimtree** [comment]
https://github.com/yamujine/artmatch/commit/9e99ab01c958adce7b73c680e25e90052410a739 여기서 적용하였습니다.
