### ISSUE TITLE
회원가입 - 페이스북 회원가입시 UI깨짐

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#176]
<img width="502" alt="2017-02-22 14 42 17" src="https://cloud.githubusercontent.com/assets/557307/23198786/4f1f0412-f90d-11e6-932d-7c10daed590b.png">

회원가입은 일반 회원가입 / 페이스북 두가지로 구성. 페이스북으로 로그인 시 UI가 위와 같이 깨집니다.
페이스북 로그인인 경우에 제대로 정보가 불러와졌다는 것을 보여주기 위해서 프로필 사진 표시 및 이메일 주소 입력으로 처리하였습니다.

**Comment by kimtree** [comment]
https://github.com/yamujine/artmatch/pull/100 머지 이후 작업해주시면 될 것 같습니다.

**Comment by mintplo** [comment]
이 부분 제가 임의로 디자인한 내용이며 앞으로 디자인되어 바뀔 예정입니다.

프로필 이미지를 조금 줄이는걸로 타협하는게 어떨까요?

**Comment by kimtree** [comment]
@mintplo 앞으로 디자일 될 예정이면 일단 놔둬도 될 것 같네요~ 프로필 이미지를 적당히 줄여도 좋을 것 같습니다.

**Comment by mintplo** [comment]
네 #100 머지 된 이후에 적당히 조절해서 커밋 올리겠습니다.
