### ISSUE TITLE
작품/장소 삭제 버튼 추가

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#177]
<img width="400" alt="2017-02-22 14 52 46" src="https://cloud.githubusercontent.com/assets/557307/23198989/96b32294-f90e-11e6-83ca-01773ae1d890.png">

위와 같은 내용에 대해서 삭제 기능을 추가해야할지 + 미노출 기능이 또 추가 되어야 할지(개인적 질문입니다.)

**Comment by thorlee** [comment]
삭제버튼은 추가되는게 맞는것 같습니다.
원래 수정/삭제 버튼은 기획서에는 있었습니다~

**Comment by kimtree** [comment]
@thorlee 삭제 기능 추가하겠습니다!

**Comment by kimtree** [comment]
https://github.com/yamujine/artmatch/pull/193 에서 작품, 장소 제거기능 추가되었습니다. 수정 버튼과 함께 삭제 버튼도 마크업 부탁드립니다.
