### ISSUE TITLE
회원 가입 후 이메일 인증 안한 회원을 위한 페이지

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#179]
<img width="1419" alt="2017-02-22 15 42 51" src="https://cloud.githubusercontent.com/assets/557307/23200064/959ca1a8-f915-11e6-9ba9-02082cda85d1.png">

이메일 인증을 안한 사람이 로그인을 한 경우 위 페이지로 리다이렉트하여 서비스를 사용하지 못하고 있습니다.
이 페이지에 접근하는 사람이 많을텐데 관련해서 디자인이 필요해보입니다.

**Comment by mintplo** [comment]
디자이너님들께 전달하여 처리하겠습니다!
