### ISSUE TITLE
static, img 서버 serving용 URL 함수 만들기

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#183]
사이트 전역에서 사용하고 있는 static/img 들을 위한 URL 생성 함수 만들기

**Comment by kimtree** [comment]
현재 nginx 상에서
static -> static 폴더에 매핑
img -> uploads 폴더에 매핑

**Comment by kimtree** [comment]
@mintplo 현재로썬 별도의 기술이 들어갈 것 같지는 않아서 서버에서 처리할 필요가 없을 것 같긴한데, 매크로로 만들거나 twig 상에서 바로 주소를 적어주는게 나으려나요?!

**Comment by mintplo** [comment]
좋은 방법입니다!

한 가지 질문이 있습니다.
값을 안넘겨도 되는 경우에도 () 이것을 넣으신 것은 통일성을 위함인가요?

**Comment by kimtree** [comment]
@mintplo 코드 관련 내용은 PR에 달아주세요. () 없으면 되는지 확인을 못했었네요. 지워도 상관 없을 것 같은데, 편한 방법 알려주시면 지우던지 놔두던지 하겠습니다.
