### ISSUE TITLE
이메일 템플릿 작성 필요

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#186]
이메일 템플릿 없이 그냥 쓰다가 스팸메일에 걸릴 확률이 조금 높아짐 따라서 비밀번호 찾기, 이메일 인증 등을 다양한 용도에 쓰일 수 있는 기본 이메일 템플릿이 필요.

**Comment by djongin** [comment]
제플린에 업로드 완료 했습니다 :)
https://zpl.io/ZYhis1
