### ISSUE TITLE
프로필 사진 없는 경우 기본 프로필 이미지

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#188]
<img width="915" alt="2017-02-22 20 46 02" src="https://cloud.githubusercontent.com/assets/557307/23210222/fc150acc-f93f-11e6-9586-458aa0e348e6.png">

남녀 구분이 없기 때문에 중성적인 이미지의 기본 프로필 이미지가 있어야 할 것 같습니다.

**Comment by kimtree** [comment]
/static/images/tom.jpg 이거 이미지 대치만 해주시면 될듯...

**Comment by mintplo** [comment]
우선순위에서는 조금 밀렸지만 곧 받아 적용하기로 했습니다!

**Comment by djongin** [comment]
[avartar.zip](https://github.com/yamujine/artmatch/files/796842/avartar.zip)

기본 프로필 이미지입니다.
avartar-border는 프로필 상단에들어갈때 쓰는거구,
avartar는  GNB 프로필에 사용하시면 됩니다.

**Comment by mintplo** [comment]
@kimbellin 외곽선 들어간건 굳이 안써도 될것같고 (코드로 처리 가능) avartar만 사용하겠습니다.
