### ISSUE TITLE
썸네일 이미지 크기 확인

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#189]
메인 목록과 작품/장소 상세 썸네일 표시할 크기가 대충 어느정도 되어야 할까요? 적당한 썸네일 크기 잡아주시면 그렇게 진행하겠습니다.

현재는 640x640 / 300x300 으로 비율 유지하여 2가지를 생성하고 있는데 적당히 하나로 통합해도 될 것 같습니다.

**Comment by mintplo** [comment]
이 부분은 잘 모르겠네요... 디자이너님들께 한번 물어보겠습니다.

**Comment by mintplo** [comment]
애기한 결과 여러 유형별로 썸네일이 제작될수도 있어서 일단 이건 캠프때 애기한 후 처리하시는게 어떨까요? 정 안되면 제가 서버 코드를 만져서라도 해결하겠습니다.

**Comment by kimtree** [comment]
@mintplo 근데 여러 유형별로 썸네일이 제작된다는게 어떤 의미일지 모르겠네요. 썸네일을 활용하는 곳은 메인(마이페이지) 또는 상세 페이지 내 하단의 두가지로 제한적인 부분에서만 사용되는데 어느 부분에서 다양한 크기로 이미지를 사용하나요?

**Comment by mintplo** [comment]
작품 사이즈가 P형, M형, F형 등 이미지 비율이 작품의 사이즈 유형별로 다를텐데 하나의 사이즈로 통일하여 썸네일을 만드는 건 보여주는 입장에서는 조금 의아합니다. 하지만 또 여러 유형별로 다른 썸네일을 만드는 것도 공수가 많이 들고 관리하기가 힘들것 같아 다른 방법이 있는지 어떻게 해결할 수 있는지 캠프때 애기하는 것이 어떨까 해서요.

그리고 방금 또 확인해봤는데 작품, 장소 상세 페이지 전시이력 보여주는 곳의 썸네일 사이즈는 비율이 메인과는 조금 다릅니다.....;;;

**Comment by mintplo** [comment]
전시이력 보여주는 곳의 썸네일 사이즈는 메인과 통일해주십사 디자이너님들께 애기드렸습니다.

**Comment by kimtree** [comment]
@mintplo 지난번에 회의때 이야기 듣고 생각해봤는데, 아래와 같습니다.

- P/M/F형의 비율이 중요하지 않습니다. 기본적으로 유저가 이미지를 올릴 때 작품을 정확히 스캔해서 올릴지, 사진을 찍어서 올릴지 알 수가 없기 때문입니다. (설치 작품인 경우는 아예 다름) 이미지 내에서 작품 영역을 찾아서 그 비율에 맞게 썸네일을 생성한다.. 비현실적으로 보입니다.
- 기본적으로 썸네일 생성은 원본의 ratio를 유지하여 썸네일 생성이 되는 것으로 알고 있고, 현재 그 옵션은 설정되어 있습니다. 하나의 사이즈로 통일하여 썸네일을 보여준다에 대한 대답이 될 것으로 보입니다. 정말 정확한 이미지를 보려면 당연히 상세에 와서 원본을 보는게 맞습니다.
- 따라서, 여기서의 논의는 비율을 유지하여 생성되는 썸네일 사이즈의 한 축이 몇 px로써 PC화면에 보여야 좋게 보일지에 대한 논의를 하고자 하는 것 입니다.

**Comment by mintplo** [comment]
비율이 유지된채 생성될 수 있다면 300X300으로 가는것이 좋을것 같습니다~

**Comment by kimtree** [comment]
@mintplo 
https://github.com/yamujine/artmatch/commit/1dcf4c52cf5e8def5e6ba438982ca3f8d7f14ef7
https://github.com/yamujine/artmatch/commit/2b7117cfb7d8538f40eaac318227a9ae556e4f1a
에서 처리하였습니다.
maintain_ratio 옵션, 세로길이 베이스로 생성하였습니다. 현재 img 태그에서 임의로 리사이즈 해서 꽉 채워 보여주는데 이 부분 CSS수정되어야 할 것 같습니다.

**Comment by mintplo** [comment]
@kimtree 넵! 맞춰서 수정하겠습니다!
