### ISSUE TITLE
프론트 - 개발 환경 설정

### ISSUE THREAD

**Issue by mintplo** [yamujine/artmatch#19]
@Nablyy @junho85 

**언어**
- Native JS
- SASS

**패키지 관리자**
- NPM
- Bower

**빌드 자동화**
-  Gulp

**프레임워크 & UI 프리셋**
- Semantic UI
- jQuery 1.x OR jquery 3.x

**Comment by mintplo** [comment]
Native JS는 ES2015 기반이 아닌 ES5로 가는게 어떨까요? (관련자 분들 모두 ES2015 능숙하시다면...)

jQuery는 1.x 버전이 아직도 널리 사용하고 있어서 선택하려는데 어떨까요?

다른 프레임워크 추천도 괜찮습니다.

**Comment by junho85** [comment]
Native JS 라는 말은 그냥 JavaScript 를 말씀하시는건가요? 즉 Vanilla JS ㅋㅋ

SASS 는 쓰라면 쓰겠나이다.

ES5 를 써야 겠죠. ES2015 (ES6) 는 써도 컨버팅을 해 줘야 브라우저 호환성을 지원 하겠죠 ㅠㅠ 환경 세팅을 잘 하면 될 듯 한데 진만님이 잘 세팅해 주시면 저는 ES2015 도 좋습니다 ㅎㅎ

npm, bower, gulp 이런거도 세팅 좀 부탁드려요 ㅠㅠ 제가 메뉴얼 찾아 보고 해도 되겠지만 뭔가 구려 질 지도 모릅니다 ㅋㅋ

http://semantic-ui.com/ 도 제가 안써봐서... 잘 이끌어 주셔요 ㅎㅎ

jQuery 는 저도 1 버전대만 주로 써봤는데 아무래도 브라우저 호환성 때문에 1.x 가 좋을듯 합니다. 2.x 는 호환성을 일부 포기 했다고 했고 3.x 는 아직 뭐가 달라졌는지 모르겠네요.

결론은 진만님이 이끌어 주시면 다 소화해서 쓰겠습니다. 세팅 및 샘플 페이지 정도 만들어 주시고 참고 자료 몇개 추천 해 주시면 좋을 듯 하네요.

**Comment by junho85** [comment]
jquery 는 마음이 바꼈습니다 ㅎㅎ
jquery 브라우저 호환성 보니 1.x 를 써야 되는 이유는 IE8 지원 때문이라고 볼 수 있는데요.

통계를 보니 2017년 1월 기준 한국 IE8 사용율이 1.46% 정도 입니다.
http://gs.statcounter.com/browser-version-market-share/desktop-tablet-console/south-korea/#monthly-201401-201701

IE11, IE8 만 캡쳐
![image](https://cloud.githubusercontent.com/assets/1219373/22718444/c06ef274-ede3-11e6-8582-6a44dfd95f05.png)

전체 브라우저 사용율 캡쳐
![image](https://cloud.githubusercontent.com/assets/1219373/22718453/d15eca50-ede3-11e6-9e7b-ccee574794bb.png)

우리 서비스를 사용하는 유저층만 따져 보면 더 적을 거라 생각이 듭니다.

고로 3.x 최신 버전을 쓰면 되겠습니다.

게다가 이미 @Genie-Youn 님이 올려주신 PR 에 3.x 쓰셨더라구요. 1.x 쓰자고 댓글 달까 하다가 좀 찾아 보니 이제는 IE8 쓸 이유가 별로 없네요.

**Comment by junho85** [comment]
하지만 아래에 의하면 아직 IE8 이 10% 정도 점유율을 차지 하고 있네요.
http://koreahtml5.kr/jsp/infoSquare/browserUseStatsKor.jsp?type_code_LIST=USST0001&os_code=all&search_type=B&search_date=201606
![image](https://cloud.githubusercontent.com/assets/1219373/22720064/08003988-edec-11e6-8320-a56082cb046a.png)

StatCounter를 다 믿지 마세요! (2)
http://blog.creation.net/591#.WJpvWraLTUJ

**Comment by mintplo** [comment]
jQuery 3.x 버전으로 선택해서 개발환경 설정하겠습니다.
