### ISSUE TITLE
메인 pick artist UI 관련

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#192]
#  AS-IS
<img width="1148" alt="2017-02-22 22 48 19" src="https://cloud.githubusercontent.com/assets/557307/23214181/13b0dcd6-f951-11e6-852a-639d76268070.png">

메인 슬라이더 우측 공백이 많이 남은데 마지막 이미지는 아래 정도까지 오도록 하는게 좋지 않을까요? 아니면 pick 아티스트 갯수를 늘릴까요?

# TO-BE
<img width="1010" alt="2017-02-22 22 49 06" src="https://cloud.githubusercontent.com/assets/557307/23214207/2e30e600-f951-11e6-92d1-376de75a34c3.png">

**Comment by mintplo** [comment]
(마지막 작품이 중간에 올 수 있는건 제 의도였습니다만...) 브라우저 사이즈가 유동적이고 PICK ARTIST 박스의 비율이 다른 작품 썸네일 사이즈와 다르기 때문에 저렇게 딱 맞추기는 힘들지만 얼추 비슷하게 막을까요?

다른 분들께 의견을 물어봐야하나요?

**Comment by kimtree** [comment]
@mintplo 다른 분들 의견 받아서 처리하면 될 것 같습니다.

**Comment by thorlee** [comment]
정확히 맞을필요는 없을것 같고 비슷하게만 막는게 더 보기 좋겠네요.

**Comment by seulsim** [comment]
지금 화살표 버튼 위치가 잘못되어 있어서 더 그렇게 보이네요 이부분 진만님이랑 검수해서 화살표 버튼 위치부터 수정하겠습니다ㅏ.

**Comment by kimtree** [comment]
진만: 처리함
