### ISSUE TITLE
git 프로젝트 프로세스 정립

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#2]
## 개요
* master 브랜치는 정식 배포용 - https://github.com/yamujine/deploy-artmatch
* develop 브랜치는 개발 배포용
* 작업은 이슈를 생성해서 작업
* 이슈마다 브랜치 따서 작업. label/#123_description. ex) feature/#2_git_process
* PR (Pull request) 날리고 코드리뷰. 아무나 1명 이상 리뷰 받으면 머지 한다. (캠프때는 시간이 촉박하면 본인이 직접 할 수도 있음)

**Comment by kimtree** [comment]
이슈별 브랜치 작업
-> feature/#1_git_process 라고 해야할 것 같습니다!

**Comment by junho85** [comment]
@kimtree 
음. 저는 feature_#1_git_process 형식으로 쓰다 보니... feature/#1_git_process 로 했을 때 어떤 장점이 있나요?

**Comment by kimtree** [comment]
아 이게 아까 철혁님이 말씀하셨던 대로 git flow 방식에서 쓰는 네이밍대로 브랜치를 저렇게 하면 sourcetree에서 폴더식으로 접어서 볼 수 있습니다~ https://answers.atlassian.com/questions/200282/sourcetree-categorize-branches

**Comment by junho85** [comment]
@kimtree 오오 그렇군요. 그렇게 수정 하겠습니다.
