### ISSUE TITLE
마이페이지 - 페이스북 링크?

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#200]
<img width="826" alt="2017-02-23 18 18 59" src="https://cloud.githubusercontent.com/assets/557307/23252828/85694030-f9f5-11e6-9ccc-0a9a87c8c3ae.png">

현재 회원 가입시에 별도로 페이스북 링크를 저장하고 있지는 않습니다. 페이스북 링크 부분은 어떻게 처리가 되어야 할지요?

**Comment by mintplo** [comment]
db에 fb_id 가 set이 되면 그걸로 링크를 생성할수 있습니다.

페이스북으로 가입한 사용자만 보여주는 링크기 때문에 괜찮지 않을까요?

**Comment by kimtree** [comment]
@mintplo 본인이 노출을 원치 않는 경우는 어떻게 하나요?

**Comment by mintplo** [comment]
글쎄요.. 회원가입이나 마이 페이지에서 페이스북 링크 노출 여부를 선택할 수는 없기 때문에 삭제가 맞는것 같습니다.

옵션이 추가된다면 나중에 링크를 추가할 수는 있지만 기획적으로는 큰 이슈가 아니기 때문에 선제적으로 삭제하고 나중에 대응하는것도 나쁘지 않을것 같습니다.

근데 개인적으로 굳이 페이스북 링크 노출 여부 옵션을 주는것보다는 아예 안보여주는게 맞는것 같아요.
