### ISSUE TITLE
아이디 길이, 태그 입력 길이 제한

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#201]
아이디: 15자 ( 영어 + (.-_) )
태그: 60자

- [x] 서버: DB 및 문자열 관련 로직 확인

- [x]  프론트: validation 로직 확인

**Comment by junho85** [comment]
이건 남우님이 하고 있는거 같으니 남우님으로 담당자 지정합니다

**Comment by kimtree** [comment]
@junho85 서버는 대충 완료되었고 프론트 확인해주세요~

**Comment by junho85** [comment]
@kimtree @mintplo @Nablyy 
혹시 프론트에서 validation check 할 때 추천 방식 있으시면 추천 부탁드립니다~
* 그냥 javascript 로직 짜고 유효하지 않으면 alert 띄운다
* 누군가 만들어 둔 validator 를 이용한다. - https://github.com/petk/awesome-jquery#validation

star 7,322 로 가장 인기 좋음
https://github.com/jquery-validation/jquery-validation

**Comment by kimtree** [comment]
https://github.com/jquery-validation/jquery-validation 요거 좋아보이네요ㅋㅋ

**Comment by junho85** [comment]
남우님이 bower.json 에 jquery-validation 넣음.
vex 도 추가 됨.

**Comment by junho85** [comment]
![image](https://cloud.githubusercontent.com/assets/1219373/23326184/b2561d94-fb3e-11e6-8c3b-895732865134.png)

![image](https://cloud.githubusercontent.com/assets/1219373/23326177/9f22bd5e-fb3e-11e6-8c96-25b232e4837f.png)

jquery-validation 적용. 디자인은 없음.
