### ISSUE TITLE
로그인한 유저의 페이지 진입시

### ISSUE THREAD

**Issue by mintplo** [yamujine/artmatch#210]
로그인한 유저

/users/me
/users/{user_id}

두 개가 따로 동작하는 특별한 이유가 없으면 /users/{user_id}로 진입할 때 /users/me로 리다이렉트 시키는 것이
어떨까요?

**Comment by kimtree** [comment]
@mintplo 두 개 링크 접속만 해보셔도 차이점이 보일텐데요.

일단 /users/<user_id>는 퍼블릭에게 보여주는 프로필 페이지이기 때문에 내 작품/장소만 강조하고, 타인에게 나의 퍼블릭 페이지가 어떻게 보이는지 인지할 수 있는 링크입니다.

/users/me는 내가 pick한 목록과 내 작품/장소를 모아 보고 유저의 프로필이나 비밀번호 설정이 바뀌는 부분이 있기 때문에 나의 private한 마이페이지가 된 것입니다.

로직상으로 통합할 여지가 많은데 이 부분은 퍼블릭 마이페이지로만 모든것을 통합하고, 내가 pick한 것만 모아보는 별도 페이지가 있는게 의미상 맞지 무조건 통합은 아니라고 봅니다.

**Comment by mintplo** [comment]
두 개의 차이점이란게 

퍼블릭과 프라이핏 페이지의 디자인이 완전 다른것도 아니고
PICK 탭 + 개인정보 변경할 수 있는 버튼만 주어지는 것이라면

굳이 로그인한 유저가 /users/me, /users/{user_id} 둘 다 볼 수 있도록 하느냐는 이해가 안됩니다.

또한 상세페이지, 댓글에서 이름을 클릭해야 /users/{user_id} 로 진입할 수 있는데  내 프라이핏 페이지를 보고 싶어서 상세페이지 진입 -> 내 이름을 클릭 이 부분도 사실 이해가 안되고

내 프라이빗 페이지가 어떻게 남들에게 보이냐를 인지할 수 있게 페이지를 보여주고 싶다면 나의 프라이핏 퍼블릭 페이지에서 전환할수 있게 버튼이 있어야 하는게 아닌가도 싶구요.

**Comment by kimtree** [comment]
다 개인적인 의견이고 결국 기획적으로 정리가 되면 해결될 문제로 보입니다. 기획 확인된거 따라서 진행하시지요.

내 프라이빗 페이지를 보기 위해서 상세 -> 내 이름을 클릭한다기 보다 GNB의 유저 아이디 클릭 + 퍼블릭 페이지에서 (마이페이지 가기) 등으로 해결할 수 있어보입니다. 애초에 기획서 상에서 공개 페이지 / 마이 페이지로 의견이 정리 되었었는데 이해가 안가시면 기획 확인을 기다리는게 맞아 보입니다.

**Comment by mintplo** [comment]
기획서 상에 공개 페이지같은 경우에는 단순히 상대방이 나의 프로필을 보고 싶을때 보여지는 페이지이지 해당 유저도 이걸 볼 수 있다고 이해한것이 아니라....

당장 확인하시기에는 힘들것 같고 캠프때 말씀을 들어보겠습니다.

**Comment by thorlee** [comment]
로그인 한 사용자가 자기의 공개페이지를 볼일이 있느냐 없느냐를 확인하는 상황인것 같습니다.
공개페이지를 꼭 보여주느냐 안 보여주느냐는 중요한 부분은 아닌것 같아서,
꼭 막을필요는 없어보이네요~(어차피 다른 ID로든 볼 수 있는 상황일거라..)
그리고 자기 공개페이지가 남들한테 어떻게 보이는지도 보고 싶을 수도 있어서요.
일단은 리다이렉트를 한다거나 접근을 제한한다거나 하는 작업은 하지 않아도 될 것 같습니다.

**Comment by mintplo** [comment]
@thorlee 그렇다면 프라이빗 페이지에서 퍼블릭 페이지로 갈 수 있는 버튼을 추가하는게 어떨까요?
