### ISSUE TITLE
등록/수정 폼 에러메시지 관련

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#211]
현재 등록시 따로 에러 메세지를 표시할 좋은 방법이 없음. https://jqueryvalidation.org/ 등을 이용하여 입력 폼에 바로 에러가 있는 경우에 폼 아래에 "! 제목을 입력해주세요." 라고 뜨면 좋을 것 같습니다.

![sample](http://technofaq.org/wp-content/uploads/2016/05/1462305262jquery_validation2.jpg.jpg)

**Comment by mintplo** [comment]
@kimbellin @seulsim 
확인 부탁드립니다.

**Comment by djongin** [comment]
제플린에 업로드 완료 했습니다 👍
