### ISSUE TITLE
미팅 - 2017.02.08 안건

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#25]
* 업무 분장
* 장소 기간 항목에 관해
* ...

**Comment by genie-youn** [comment]
이미지를 어떻게 처리할것인지? 에 대한 논의도 필요할것같아요

**Comment by junho85** [comment]
썸네일 두개 만들고 디자이너가 사이즈 정해주면 정해준 사이즈로 한다.

**Comment by junho85** [comment]
일단 서버 프론트 구분 없이 화면 하나씩 잡고 만들기로 했습니다~ (아직 디자인이 안나와서 마크업이 어렵고 프론트 작업도 어려운 상태라 마크업 없는 기본 기능 정도까지만 구현)

궁금한거 논의 할건 중간중간 메신저로 알려 주시고.
다음모임은 토요일 오후 두시 입니다.

지수
로그인
회원가입

남우
작품등록

현영
작품목록

진만
장소등록

준호
장소목록
