### ISSUE TITLE
목록에서 pick 버튼이 안보임

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#258]
![image](https://cloud.githubusercontent.com/assets/1219373/23329974/4c018e68-fb87-11e6-82c0-ca324b11588f.png)
pick 기능 동작은 잘 되고 있는 것으로 보임

**Comment by kimtree** [comment]
css의 static 이미지 관련 링크 오류. 실서버에 맞춰서 수정하다보니 생긴 버그

**Comment by kimtree** [comment]
https://github.com/yamujine/artmatch/commit/8cb17594fa41e705039d1984cea77591e3c7153e 에서 원복. 서버에서는 야매로 rewrite rule 추가
