### ISSUE TITLE
더보기 친구들 pick이 안되는 버그

### ISSUE THREAD

**Issue by genie-youn** [yamujine/artmatch#268]
더보기해서 생긴 엘리먼트들의 pick을 눌러도 적용이 되지 않습니다!

**Comment by junho85** [comment]
기존리스트 pick 과 더보기리스트 pick 의 차이점?

더보기버튼 class patItemMoreButton

http://localhost:8080/api/contents/list?type=artworks&offset=9&limit=9



기존
main.twig

$(this).find('.pickBtn').click(function () { ... 으로 이벤트를 붙임.

그런데 아마 더 보기로 불러온 데이터들은 pickBtn 에 이벤트를 안붙여서 그럴 듯 함.
