### ISSUE TITLE
전시요청탭에서 승인

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#281]
## 개요

서버: https://github.com/yamujine/artmatch/issues/234
마크업:

후속 작업

## 페이지
http://localhost:8080/users/me?show_applied_list=1

## 관련파일
Users.php
me 함수에서
show_applied_list === 1 이면 _applied_list 함수 실행

**Comment by kimtree** [comment]
https://github.com/yamujine/artmatch/commit/b54b69d06589f7afe7f9f9ecbd1d4fb36f6061c4
