### ISSUE TITLE
마이페이지 - 탭이 왼쪽으로 치우침

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#283]
다른 화면은 탭이 가운데에 있는데 마이페이지는 왼쪽으로 치우쳐서 이상해 보임

http://localhost:8080/users/me?show_applied_list=1
![image](https://cloud.githubusercontent.com/assets/1219373/23335769/c9e352bc-fbff-11e6-9293-f78ef5e7dcee.png)

http://localhost:8080/users/me
![image](https://cloud.githubusercontent.com/assets/1219373/23335773/dba3a2ae-fbff-11e6-8852-dc4b05b0dc00.png)

**Comment by mintplo** [comment]
프로필도 같이 좌측으로 배치하면서 괜찮아져씁니다!
