### ISSUE TITLE
비밀번호 찾기 이후 redirect가 필요할것 같습니다

### ISSUE THREAD

**Issue by genie-youn** [yamujine/artmatch#297]
<img width="1274" alt="2017-02-26 2 39 04" src="https://cloud.githubusercontent.com/assets/16642635/23337441/5ae7db30-fc31-11e6-85b6-21b3bcd4c09f.png">

**Comment by kimtree** [comment]
develop에 머지했고, 실서버 반영 전까지는 이슈 클로즈 하지 말아주세요~

**Comment by genie-youn** [comment]
넵 확인했습니다.
