### ISSUE TITLE
서버 - 회원관련 기능 개발

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#3]
ion-auth 가 무난한듯?
https://github.com/benedmunds/CodeIgniter-Ion-Auth

facebook 소셜로그인 붙이자

요런게 있던데 여전히 잘 되는지는 모르겠음
https://github.com/dgeorgiev/facebook-ion-auth

안되면 이런거 참고
http://hybridauth.sourceforge.net/

**Comment by kimtree** [comment]
1차 작업 범위
- 로그인
- 회원가입 (2가지 - 일반 / 페이스북 로그인 후 추가 정보 입력)
- 비밀번호 찾기

**Comment by genie-youn** [comment]
- [x] 로그인

- [x] 회원가입

- [ ] 페이스북 회원가입

- [ ] 비밀번호 찾기

**Comment by junho85** [comment]
종료 합니다. 추가 작업은 이슈 생성해서 해 주세요~
