### ISSUE TITLE
미팅 - 2017.02.11 (토) 안건

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#30]
* 컨벤션 - X
```
class Artworks extends MY_Controller
{
	public function detail($artwork_number)
	{
		echo $artwork_number . ' artwork detail';
	}

	public function upload()
	{
```
https://www.codeigniter.com/user_guide/general/styleguide.html 가이드에 의하면 class 만 옆에 쓰고 나머지는 밑에 쓰고 있음.

우리는 다 옆에 붙여 쓰자 - OK
```
class Artworks extends MY_Controller {
	public function detail($artwork_number) {
		echo $artwork_number . ' artwork detail';
	}

	public function upload() {
```
* API 형식 - pass
* API 사용 할 곳 - pass

* PR 이 오래 남는 경우가 종종 있음

* 코드리뷰
  * 장소, 작품 페이징? 더보기? 기획 문의

redirect 문제
8080
localhost:8080/places/upload
localhost/index.php/places
base 경로에 

ui 는 진만님 위키에 정리 https://github.com/yamujine/artmatch/wiki/%ED%94%84%EB%A1%A0%ED%8A%B8-%EC%A0%95%EB%A6%AC

* 할 일 할당
  * [ ] 회원 - 지수
  * [ ] 장소 - 목록에서 검색기능 - 준호
  * [ ] 작품 - 목록에서 검색기능 - 준호
  * [ ] 장소 - 상세정보보기에 pick - 현영
  * [ ] 작품 - 상세정보보기에 pick - 현영
  * [ ] 작품 - 수정페이지 - 남우
  * [ ] 장소 - 수정페이지 - 준호
  * [ ] 프론트 세팅 - 진만
* TODO
  * [ ] 관리자 페이지 - 장소, 작품 맵핑
  * [ ] my 페이지 - 내가 픽한거 등등
  * [ ] 작품 - 댓글기능
  * [ ] 장소 - 댓글기능

* 다음회의 - 2017년 2월 18일 토요일 오후 2시

**Comment by kimtree** [comment]
Encryption - https://codeigniter.com/userguide3/libraries/encryption.html#supported-hmac-authentication-algorithms

**Comment by kimtree** [comment]
@junho85 기획서에 있는 것 처럼 메인 페이지에서 간단한 검색 기능 구현해서 develop 브랜치에 넣었습니다. 기획 더 자세히 나오면 참고해서 작업해주시면 될 것 같습니다.
