### ISSUE TITLE
남의 공간인데 장소 등록하기 / 작품 등록하기 메뉴 노출

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#305]
![kakaotalk_photo_2017-02-26-15-12-49](https://cloud.githubusercontent.com/assets/557307/23337570/0c79a0c8-fc36-11e6-9478-09255e48cdf3.png)

**Comment by nablyy** [comment]
누군가 이슈 처리한건가요?! develop 에서 확인해봤는데 안뜨네요~

**Comment by kimtree** [comment]
@Nablyy https://github.com/yamujine/artmatch/commit/a38231f3c1d238c3c3fcaa7a22738b16e2fc347c 아까 여기서 해결했는데 업데이트를 안해놨네요~
