### ISSUE TITLE
실서버 디버깅 용 모니터링 서비스 도입

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#310]
- 진만님 추천 https://rollbar.com/pricing/

- else?

**Comment by nablyy** [comment]
https://www.whatap.io/
여긴어때요?

**Comment by kimtree** [comment]
@Nablyy 혹시 저거 php error뜨면 stack trace도 잘 지원하나요?! 일반적인 서버만 모니터링 하고 서비스 모니터링이 안되는거 같아서요~

**Comment by mintplo** [comment]
whatap은 성능 모니터링만 해주는것 같습니다.

**Comment by kimtree** [comment]
sentry - Hobbist로 하면 1계정 10k events/month https://sentry.io/pricing/

**Comment by kimtree** [comment]
이번 배포시에 빠른 디버깅을 위해서 같이 적용되면 좋을 것 같네요~!
