### ISSUE TITLE
페이스북 access token 세션에 저장하는 이유 확인 요청

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#311]
페이스북 로그인시 access token을 js로 부터 받아서 필요한 내용을 처리하는 것으로 알고 있습니다.
그리고 중간에 $this->accountlib->generate_facebook_access_token_session($accessToken); 이런식으로 accessToken을 세션에 저장하는데, 딱히 활용하는 곳이 있는지 모르겠습니다.

short-lived 가 아닌 long-lived 토큰은 나중에 정보 업데이트 용으로 DB에 보관하면 쓸모가 있을 것 같습니다만, short-lived 토큰은 따로 세션에 저장하지 않아도 될 것 같습니다.

**Comment by genie-youn** [comment]
확인했습니다. usersapi와 account외엔 사용안할것 같아서 의견 반영해서 변경하도록 하겠습니다.
