### ISSUE TITLE
https 지원

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#313]
## 개요
사용자들의 소중한 개인정보 보호를 위한 작업 중 하나인 https 적용을 했으면 좋겠습니다.

## 브라우저에서 표시 되는 상태
크롬
로그인페이지
![image](https://cloud.githubusercontent.com/assets/1219373/23352340/e3ede8c4-fd09-11e6-8044-850969a11048.png)

메인페이지
![image](https://cloud.githubusercontent.com/assets/1219373/23352359/016013dc-fd0a-11e6-9df8-b34f4fdb1c4c.png)

## 작업
* [x] 인증서 받기
* [x] 인증서 세팅
* [ ] https 로 접속

## 무료인증서
Let's Encrypt
https://letsencrypt.org/
무료이나 90일만 유지 되어서 새로 주기적으로 새로 받아서 세팅 해야 됨.

Comodo Free SSL
https://www.gogetssl.com/domain-validation/comodo-free-ssl/

CloudFlare One-Click SSL
https://www.cloudflare.com/ssl/

유효기간 자동 갱신

AWS Certificate Manager
https://aws.amazon.com/ko/certificate-manager/

유효기간 자동 갱신

## 유료인증서
업체 마다 가격이 다름

gabia 에서 인증서 설치 대행
https://sslhosting.gabia.com/service
![Uploading image.png…]()

## 비권장 인증서
startcom startssl
무료 SSL 로 유명했던 이스라엘 업체였지만 중국 WoSign 에 인수된 이후 신뢰도가 떨어졌다고 함
파이어폭스, 크롬에서 더 이상 신뢰하지 않을 예정이라고 함

self-signed 인증서
직접 생성하는 것
신뢰할 수 없다고 경고가 뜨게 됨

## 참고
SSL 인증서를 무료로 발급받는 몇 가지 방법 2016.10.26
https://blog.sysbot32.com/2016/10/26/ssl-%EC%9D%B8%EC%A6%9D%EC%84%9C%EB%A5%BC-%EB%AC%B4%EB%A3%8C%EB%A1%9C-%EB%B0%9C%EA%B8%89%EB%B0%9B%EB%8A%94-%EB%AA%87-%EA%B0%80%EC%A7%80-%EB%B0%A9%EB%B2%95/

**Comment by kimtree** [comment]
@junho85 Cloudflare는 SSL 뿐만 아니라 CDN도 겸용하고 있어서 static serving이 많은 우리 서비스에게 괜찮은 방법 일 수는 있는데 무료 버젼인 경우는 DNS 설정을 다 cloudflare에 위임해야합니다!
lets encrypt는 90일마다 갱신이 필요하지만 https://certbot.eff.org/ certbot을 이용하면 cron을 돌리는 것으로 자동 갱신이 가능하고 설정이 꽤나 편리하긴 하더라구요~

**Comment by kimtree** [comment]
Let's Encrypt로 서버에 1차 적용
- static / img URL serving할 때 protocol 의존성 없이 출력되도록 변경해야함!
