### ISSUE TITLE
메타 태그 적용

### ISSUE THREAD

**Issue by mintplo** [yamujine/artmatch#316]
링크 공유시 사용되는 썸네일 이미지등 필요한 메타 태그 등을 적용하면 좋을것 같습니다.

어떤 링크를 공유하면 무엇이 보여야 하는지 등은 논의해보는게 좋을것 같아요.

**Comment by kimtree** [comment]
keywords도 추가해주면 좋을 것 같습니다.

- 프로필: 프로필 이미지
- 상세 페이지: 대표 이미지
- 다른 페이지: 로고

대충 이정도만 되도 충분할 것 같네요.
