### ISSUE TITLE
관리자 전시이력 매핑기능 페이지 만들기

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#33]
## 개요
![image](https://cloud.githubusercontent.com/assets/1219373/22763630/6eea9770-eea9-11e6-9ee3-c81cbb7d5608.png)
관리자가 전시이력 맵핑 할 수 있는 페이지를 만든다.
추후 요청, 승인 절차 정립 필요.

## 참고
https://www.facebook.com/photo.php?fbid=1422860224430672&set=p.1422860224430672&type=3&theater

**Comment by kimtree** [comment]
1.1 버젼에서 자동화 처리
