### ISSUE TITLE
optimize images

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#338]

**Comment by kimtree** [comment]
<img width="1025" alt="2017-02-28 15 40 49" src="https://cloud.githubusercontent.com/assets/557307/23394409/4b9dd584-fdcc-11e6-9403-a96e948b8916.png">

**Comment by junho85** [comment]
PageSpeed Insights!
https://developers.google.com/speed/pagespeed/insights/?hl=ko&url=pickartyou.com&tab=desktop
