### ISSUE TITLE
장소 상세 > 전시 등록 페이지

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#342]
![image](https://cloud.githubusercontent.com/assets/1219373/26057976/c4f75f06-39b6-11e7-991c-c9e73f697e70.png)

**Comment by kimtree** [comment]
@junho85 확인해보니까 현재 exhibition_model에 title 부분이 없는데 일단 내용 API로 넘겨주시면 나중에 등록/수정 될 수 있게 변경하겠습니다! 지금은 기존에 전시 1개를 기준으로 코드 작성된 부분이 많아서 차근차근 의존성 다 제거해야할 것 같네요ㄷㄷ

**Comment by junho85** [comment]
@kimtree db table 에도 title 이 없네요. 컬럼 추가도 부탁드려요~

**Comment by junho85** [comment]
![image](https://user-images.githubusercontent.com/1219373/26968590-87695262-4d3d-11e7-9ec0-a716951ed12f.png)
누락된것 맞음. 추가 해야야 됨. 기존 places 테이블에 있던 것을 exhibitions 로 옮겨야 됨.

with 철혁님
