### ISSUE TITLE
장소 상세 > 전시 목록 표시

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#344]
## 개요
해당 섹션이 추가됨
    - 전시 리스트
    - 지금 전시중

## AS-IS
![image](https://cloud.githubusercontent.com/assets/1219373/26281229/fcd0b12e-3e2b-11e7-8a67-bff64f9ad129.png)

## TO-BE
![image](https://cloud.githubusercontent.com/assets/1219373/26281230/03908caa-3e2c-11e7-9e15-4aae9c641618.png)

**Comment by junho85** [comment]
@kimtree 
지금 전시중이에요 API 도 부탁 드립니다.
첫페이지 나올때는 상관 없는데 02 페이지로 넘어 갈 때는 API 호출 해서 새로 그려주는게 좋겠습니다.

**Comment by kimtree** [comment]
https://github.com/yamujine/artmatch/pull/361 에서 API 추가됨
