### ISSUE TITLE
마크업 - 장소 상세 > 전시 목록 표시

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#350]
## 개요
관련작업: 장소 상세 > 전시 목록 표시 #344

## AS-IS
![image](https://cloud.githubusercontent.com/assets/1219373/26281229/fcd0b12e-3e2b-11e7-8a67-bff64f9ad129.png)

## TO-BE
![image](https://cloud.githubusercontent.com/assets/1219373/26281230/03908caa-3e2c-11e7-9e15-4aae9c641618.png)

전시목록은 comment (macro/comment.macro.twig) 처럼 macro 로 만들어서 사용하자
macro/exhibition.macro.twig

## css structure
* exhibitionArea (div)
  * title
  * divider
  * exhibitions (ul)
    * li
      * content div 
        * title
        * status (없음/전시중) - 백엔드에서? 프론트에서 판단?
        * meta (startdate ~ enddate) | 작품수 exhibition.count
        * buttons
          * button(지원하기 버튼)

**Comment by junho85** [comment]
휴; 오늘은 여기까지.
![image](https://cloud.githubusercontent.com/assets/1219373/26284736/107d59a6-3e7d-11e7-939d-9e09c81f5c76.png)

**Comment by junho85** [comment]
![image](https://cloud.githubusercontent.com/assets/1219373/26313954/6861f6ca-3f47-11e7-8392-0a123bed5a31.png)

DONE
* 전시기간이랑 작품수 사이의 바
* 지원하기 버튼 > 이미지

TODO
* [x] 지금 전시중이에요!

**Comment by nablyy** [comment]
전시 없을 경우 작업하고 있습니다.

**Comment by nablyy** [comment]
![default](https://cloud.githubusercontent.com/assets/15205778/26347627/1c274ec4-3fe5-11e7-85a8-ca1057062bde.PNG)
전시목록 없을 경우
일단 제플린에서 보이는 px에 맞춰서 했는데 빨간글자가 약간 위에 몰려있는게 아닌가하는 생각이 듭니다

**Comment by junho85** [comment]
헛. 작업 한고 branch 만든다는게 안만들고 push 날렸었네요 ㅡ.,ㅡ; 망...
지금이라도 브랜치를 따겠습니다;;

**Comment by junho85** [comment]
지금 전시중이에요!
![image](https://cloud.githubusercontent.com/assets/1219373/26405733/2f9c37a2-40d1-11e7-8ee9-1c75aa7c49b6.png)

**Comment by nablyy** [comment]
전시목록 없을 경우 머지 완료했습니다
