### ISSUE TITLE
프론트 - 장소 상세 > 전시 목록 표시

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#356]
## 개요
* [x] 전시 목록
* [x] 지금 전시중이에요

**Comment by junho85** [comment]
![image](https://cloud.githubusercontent.com/assets/1219373/26526683/5ef92778-43bd-11e7-9854-ed77a57a8b6a.png)

**Comment by nablyy** [comment]
## 추가 세부 작업
### 지금전시중이에요
- [ ] 한 작가가 여러 작품 전시할 경우 이름 중복 처리
- [ ] 작가 이름 목록 범위 벗어날 경우 처리
- [ ] 지원하기 URL 처리
- [ ] 작품 수 (전시중/모집중) 처리

**Comment by junho85** [comment]
개선작업은 별도 이슈로 분리 합니다.
프론트 - 장소 상세 > 전시 목록 표시 - 개선 작업 #395
