### ISSUE TITLE
마크업 - 장소 상세 > 전시 등록 페이지

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#357]
## 개요
![image](https://cloud.githubusercontent.com/assets/1219373/26454297/acf4eaf2-41a1-11e7-97a2-0410e2149ba0.png)
* 우측 상단 취소/완료 버튼은 제거
* 주소: /places/<place_id>/exhibitions 로 변경됨

**Comment by kimtree** [comment]
주소: /places/exhibitions/<place_id> 로 접근 가능

**Comment by junho85** [comment]
@kimtree 
/places/<place_id>/exhibitions
가 좋을거 같습니다.

지원하기 URL 은 요런식으로 갈 수 있도록
/places/<place_id>/exhibitions/<exhibition_id>/apply

**Comment by kimtree** [comment]
@junho85 현재 다른 URL들이
$route['places/edit/(:num)'] = 'places/edit/$1';
$route['places/delete/(:num)'] = 'places/delete/$1';
$route['places/apply/(:num)'] = 'places/apply/$1';
$route['places/exhibitions/(:num)'] = 'places/exhibitions/$1';
이런식으로 구현되어 있어서 일단 형태를 유지하긴 했는데 개선 이슈로 분리해서 처리하겠습니다~

**Comment by junho85** [comment]
![image](https://user-images.githubusercontent.com/1219373/27009174-87cb0ec2-4ec2-11e7-9537-c6df4b8e1f4c.png)

기존 입력폼 참고고
![image](https://user-images.githubusercontent.com/1219373/27009196-2aea5360-4ec3-11e7-85bd-5d285f2764b3.png)

남은작업
* [x] 타이틀 누르면 장소 상세로 이동
* [ ] 새로운 전시 등록 하기 누르면 입력 폼 나오도록
* [x] 전시 입력/수정 폼
* [x] 전시비 지급/지급안함 추가
* [x] 버튼 작업
* [ ] 등록된 전시/종료된 전시 갯수

**Comment by junho85** [comment]
새로운 전시 등록 하기 누르면 입력 폼 나오도록
등록된 전시/종료된 전시 갯수
이건 프론트/백엔드 작업 에서 하는게 좋겠음

**Comment by junho85** [comment]
![image](https://user-images.githubusercontent.com/1219373/27258038-c9ebfdc2-5429-11e7-9fa2-1ffaed020342.png)
수정, 삭제, 완료 버튼이 좀 이상한데 저건 따로 개선 작업 해야 겠음.

**Comment by junho85** [comment]
개선이슈
마크업 - 장소 상세 > 전시 등록 페이지 개선 #373
