### ISSUE TITLE
마크업 - 장소 상세 > 작품 지원

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#358]
## 개요
![image](https://cloud.githubusercontent.com/assets/1219373/26526552/621fdde6-43ba-11e7-94cb-a0f1d7083a13.png)

## 작업
* [x] 지원하기 페이지를 장소 기준이 아닌 전시회 기준으로 변경
* [x] static 경로 제대로 못찾아 가서 수정
* [x] 타이틀
* [x] 전시명
* [x] 이유 textarea
* [x] 지원작품 선택

**Comment by junho85** [comment]
![image](https://user-images.githubusercontent.com/1219373/28050829-0cf76886-663b-11e7-8e04-d8d075744496.png)

**Comment by junho85** [comment]
url ex) http://localhost:8050/exhibitions/71/apply/
지원 이유는 좀 늘렸음.

**Comment by mintplo** [comment]
코드 수정 및 개수 선택 관련 스크립트 추가했습니다.
