### ISSUE TITLE
[DB] 스키마 변경

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#368]
DB 관리
- exhibitions : 지원가능여부(status) 필드 추가 필요
- places : status 칼럼 제거

**Comment by junho85** [comment]
@kimtree 
지원가능여부니까 status 보다는 is_free 처럼 is_appliable 이 좋을거 같습니다. status 가 주로 전시중 등의 의미로 쓰여서 지원가능여부가 status 인게 혼란을 주네요.
