### ISSUE TITLE
프론트 - 작가 마이페이지 -> 지원한 전시

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#398]
## 개요
관련작업
마크업 - 작가 마이페이지 -> 지원한 전시 #375 

## 관련파일
* Controller: Users.php
  * apply_status
    * exhibitions => $exhibition_list
* Model: Artwork_model.php
* view: users/apply_status.twig

## 작업
테스트url: http://localhost:8050/users/junho85/apply_status

* [x] 지원한 전시 총n개
* [x] 총 n개의 작품
* [x] 작품 보기/닫기
* [x] 진행상황별 class 변경
  * 작품 모집중, 모집종료, disable(전시종료)
* [x] 지원여부별 class 변경
  * 지원완료, 취소완료, 전시확정, 선택안됨, disabled(전시완료, 선택안됨)
* [x] "지원완료"인 경우 "지원취소" 버튼
* [x] "취소완료"인 경우 "다시지원" 버튼 - 취소완료는 없음. row 를 삭제함. 상태가 없음.
* [x] 지원취소
```
$route['api/exhibition/cancel_apply']['POST'] = 'exhibitionApi/cancel_apply';
```
* [x] 다시지원 - 취소완료가 없어서 다시지원도 없음.
* [ ] tr disabled 처리
* [ ] ...

**Comment by kimtree** [comment]
취소 API
POST /api/exhibition/cancel_apply
apply_id - 작품 1건당 지원 아이디 1개
전시에 작품별로 지원이 처리되는데, 해당 전시에 지원한 작품을 일괄 취소할지 각 작품만 취소할지 결정 필요

**Comment by junho85** [comment]
일괄 취소
apply_id -> exhibition_id 로 감

**Comment by junho85** [comment]
브랜치를 안따고 작업 해서 그냥 push 해 버림
`2c91dc7` 지원한 전시 갯수, 작품 갯수 - june.kim
`64480d8` table header color 변경 - june.kim
`7635c89` 작품 보기/닫기 - june.kim
`f03dd21` 진행상황별 class 적용 - june.kim
`e4fe725` 지원여부별 class 변경 - june.kim
`80bd4a4` "지원완료"인 경우 "지원취소" 버튼 - june.kim
`59f1a6c` 지원 취소 함수 작업중 - june.kim
`9f00de4` Merge branch 'develop' of github.com:yamujine/artmatch into develop - june.kim
`d17733a` Merge branch 'develop' of github.com:yamujine/artmatch into develop - june.kim
`95cddc9` 지원 취소 confirm 창 - june.kim

**Comment by junho85** [comment]
남은 작업은 이슈 분리

**Comment by junho85** [comment]
취소하고 나니 목록이 없으니 오류남
http://localhost:8050/users/junho85/apply_status
![image](https://user-images.githubusercontent.com/1219373/28238669-a250255c-6993-11e7-98f9-0bee932f343a.png)
이슈분리: https://github.com/yamujine/artmatch/issues/403
