### ISSUE TITLE
프론트 - 장소제공자 마이페이지 > 지원작가

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#399]
## 개요
관련작업
마크업 - 장소제공자 마이페이지 > 지원작가 #374

## 관련
* test url
  * http://localhost:8050/users/junho852/apply_status
  * http://localhost:8050/users/junho852/apply_status?exhibition_id=71
* 컨트롤러: Users.php
  * apply_status 함수
    * exhibition_id
    * exhibitions
    * selected_exhibition
    * artists
* css: mypage.scss

채택 API
POST /api/exhibition/accept
applied_artwork_ids
exhibition_id

## 작업
* [x] 전시명선택시 url 변경
* [x] 전시기간
* [x] 작품 선택 기능
* [x] 이 작가 전체 작품 선택
* [x] 작가확정 버튼
* [x] 확정 후 확정 된 내역은 체크 된 상태로 보여 주기
* [x] 확정 시 취소 안된다는 메시지

**Comment by kimtree** [comment]
채택 API
POST /api/exhibition/accept
applied_artwork_ids 
exhibition_id

**Comment by junho85** [comment]
일단 애매한 부분은 생략 질문으로 단톡방에 던짐
확정 한 내역은 

```
https://zpl.io/1lzmUl
의 "지원현황" 관련 질문입니다.

* 앞에 세장 탭 이름이 "지원현황" 이 맞겠죠? 두번째 장은 "지원작가"로 되어 있어서요.
* 두번째 장에 일부 사진이 disabled 처리 된 것들이 있는데 어떤 경우인가요? 선택 확정된 경우인가요?
* 두번째 장에 "선택 취소" "작가 확정" 버튼 이미지가 없는데 이건 이미지 누락인가요?
* 총 지원작품 n개 우측의 메일쓰기는 모든 작가에게 메일 보내기 인가요? 그 우측의 선택 버튼은 작가 구분없이 모든 작품에 대한 선택/취소 처리
* "작가 확정" 버튼 왼쪽에 있는 "선택 취소"는 전시회 선택 취소 인가요?
```

**Comment by junho85** [comment]
일단 요정도
확정 된 내역도 반투명 상태가 아니고 체크 상태로 처리 했음. disabled 는 먹혀 있어서 체크 해제는 할 수 없음
![image](https://user-images.githubusercontent.com/1219373/28244353-88020662-6a23-11e7-8a24-e4aa575b0a4c.png)

**Comment by junho85** [comment]
답변
![image](https://user-images.githubusercontent.com/1219373/28244936-af77696a-6a34-11e7-9dde-038f52628c7d.png)

작업할거
* 한번 확정하면 수정 안됨. (현재 작업 상태: 취소는 안되고 추가 확정은 가능 하게는 해 둔 상태)
* 확정 후 화면에서 선택 안된 작품 흐리게처리 (현재 작업 상태: 선택된 작품에 체크, 선택 안된 작품은 보통 상태)
* 확정 후 화면에서 "선택" 드롭다운 비활성화
* 전체작가에게 메일 보내기 추가
* 작품 n개 선택 문구 처리
* 총 전시할 작품 n개 확정 문구 처리

이슈분리: 프론트 - 장소제공자 마이페이지 > 지원작가 - 개선작업 #413
