### ISSUE TITLE
서버 - DB 임시 설계

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#4]
## 개요
아직 기획이 안나와서 기본적인 설계만 한다.

대충 생각해 보면
회원정보 - ion auth 참고 해서 만들기
작품정보 - 하나의 작품에 사진 여러개 올릴 수 있어야 할 수 있음
공간정보 - 하나의 공간에 사진 여러개 올릴 수 있어야 할 수 있음

**Comment by kimtree** [comment]
<img width="773" alt="2017-02-09 01 14 12" src="https://cloud.githubusercontent.com/assets/557307/22745827/30c9dac6-ee65-11e6-8758-e3a6e6cc42b1.png">
최종 DB 스키마
