### ISSUE TITLE
프론트 - 장소제공자 마이페이지 > 지원작가 - 개선작업

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#415]
## 개요
관련작업
프론트 - 장소제공자 마이페이지 > 지원작가 - 개선작업 #413

## 작업
* 확정후
  * [x] 확정 후 화면에서 선택 안된 작품 흐리게처리 (현재 작업 상태: 선택된 작품에 체크, 선택 안된 작품은 보통 상태)
  * [x] 확정 후 화면에서 "선택" 드롭다운 비활성화
* 선택 드롭다운 작업
![image](https://user-images.githubusercontent.com/1219373/28245473-b63a9d7c-6a42-11e7-84b2-316b44c50608.png)
* [x] "이 작가 작품 전체선택" 시 버튼 색 파란색. 전체 선택 상태 아니면 흰색버튼.
![image](https://user-images.githubusercontent.com/1219373/28245838-53da17c2-6a4a-11e7-9ce4-62a0e5af2e27.png)

**Comment by junho85** [comment]
![image](https://user-images.githubusercontent.com/1219373/28245854-95c03fb8-6a4a-11e7-8447-6b092c3f96c9.png)
확정 시 확정안된작품들은 탈락처리 될 듯 함.

**Comment by kimtree** [comment]
작가의 지원하기 페이지처럼 UI가 통일감 있으면 좋을 것 같습니다.
<img width="941" alt="2017-07-17 15 41 28" src="https://user-images.githubusercontent.com/557307/28257521-6b2702fc-6b06-11e7-86e8-e2e9b63549db.png">
