### ISSUE TITLE
지원하기 기획 확인

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#421]
![2017-07-20 15 19 21](https://user-images.githubusercontent.com/557307/28403238-d943a678-6d5e-11e7-80be-76952e1658fa.png)

현재는 지원하기 페이지를 여러번 진입할 수 있고, 매번 작품을 추가로 지원이 가능하고, 기존에 지원한 작품을 취소할 수 없음. 

지원하기 이유는 매번 다르게 입력해서 넘길 수 있지만 실제로 전시 1개에 지원할 때 1개의 이유만을 사용하므로 의미가 없기 때문에 기획 정리가 필요.

**Comment by thorlee** [comment]
지원한 내역이 있을 경우에는 "지원한 이력이 존재합니다. 작품의 추가 지원만 가능하고 지원하는 이유는 마지막 이유로 노출됩니다." 라고 alert를 뛰우고, 가장 마지막 이력을 사용하는 것으로 정리하면 될 것 같습니다.

**Comment by kimtree** [comment]
![2017-07-29 15 24 25](https://user-images.githubusercontent.com/557307/28742698-038f3bee-7472-11e7-80a7-a5bb7384326e.png)
@thorlee 
- Alert 대신에 지원하는 이유 입력란 윗쪽에 안내 문구 추가 
- 지원하는 이유에 최근에 입력한 이유 표시 하도록 수정하였습니다.
