### ISSUE TITLE
작품 확정 후 작가에게 알리는 방법 필요

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#422]
작품을 지원하는 경우에 장소의 소유자에게 ~~ 작품이 지원되었습니다. 메일이 아래와 같이 보내지고 있음.
<img width="523" alt="2017-07-21 16 30 10" src="https://user-images.githubusercontent.com/557307/28453336-e00ba784-6e31-11e7-88ee-b43ff29abdb0.png">

하지만, 장소 소유자가 작품을 확정하는 경우에 작가에게 별도의 알림이 보내지지 않음. 
이 경우에 장소 소유자가 알아서 컨택을 해야할지 / 작가에게도 선정되었다고 알림을 보내줘야 할지 결정이 필요할 것 같습니다. (또는, 작가의 지원 현황에서 "전시 확정"이라고 표시되어있는 부분에 장소 소유자 연락처를 공개한다거나)

**Comment by thorlee** [comment]
확정이 될경우에 UI상의 변화는 없고, 
기본적으로는 장소 소유자가 알아서 컨택을 하는 것으로 하고
다만 확정이 되면 "지원한 작품이 확정되었습니다" 라는 내용으로 메일로 지원자에게 안내하는 것으로 하면 좋겠습니다. 즉 UI상에서 변화는 없고 확정시에 메일만 발송되는 것으로 합니다.

**Comment by kimtree** [comment]
<img width="789" alt="2017-07-28 18 01 39" src="https://user-images.githubusercontent.com/557307/28710531-43da616e-73bf-11e7-9dc7-2f0627e856cc.png">
