### ISSUE TITLE
서버 - 서버 세팅

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#5]
## 개요
서버 나오면 서버 세팅 한다.
아마 2월 1일 나올 듯 하다.

## 작업
* [x] 웹서버 설치
* [x] DB 설치
* [x] 배포 세팅

**Comment by kimtree** [comment]
1. 웹서버
soruce.list -> ftp.daumkakao.com 으로 주소 변경
apt-get dist-upgrade (커널 포함 업그레이드 진행)
* Nginx 1.10.3 (stable)
http://nginx.org/en/linux_packages.html#stable
/etc/apt/sources.list.d/nginx.list 추가
```apt-get install nginx```
  * php-fpm 연동을 위한 nginx 유저를 www-data로 추가
```sudo usermod -aG www-data nginx```
  * nginx - php7.0-fpm 연동
```/etc/nginx/sites-enabled/pickartyou``` 참고

* PHP 7.0 (Ubuntu 16.04 기본)
```apt-get install php php-mysql```
Currently installed modules
```calendar, Core, ctype, date, exif, fileinfo, filter, ftp, gettext, hash, iconv, json, libxml, mysqli, mysqlnd, openssl, pcntl, pcre, PDO, pdo_mysql, Phar, posix, readline, Reflection, session, shmop, sockets, SPL, standard, sysvmsg, sysvsem, sysvshm, tokenizer, Zend OPcache, zlib```
  * Timezone Asia/Seoul 설정
```/etc/php/7.0/fpm/php.ini:924```
```/etc/php/7.0/cli/php.ini:924```

* 사용자 계정 추가
```adduser pickartyou```
```usermod -aG sudo,www-data pickartyou```

2. DB 설치
* MariaDB 10.1 (stable)
https://downloads.mariadb.org/mariadb/repositories/#version=10.1&mirror=kaist
```apt-get install mariadb-server```
  * Character set 설정
```/etc/mysql/conf.d/mariadb.cnf:6,14,15,16,17```
  * 외부(mysqlworkbench 등)에서 접속 가능하도록 bind-address *로 설정
```/etc/mysql/my.cnf:47```
  * 데이터베이스 생성 및 권한 추가
```mysql -u root -p```
```USE mysql;```
```CREATE DATABASE *DB명* DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;```
```CREATE USER '*아이디*'@'%' IDENTIFIED BY '*비밀번호*';```
```GRANT ALL PRIVILEGES ON '*DB명*'.* TO '*아이디*'@'%';```

3. 배포 세팅
* 소스 clone (SSH가 아닌 HTTPS로 해야함)
```git clone https://github.com/yamujine/artmatch.git webroot``` webroot 폴더로 clone
* deploy-bot 설치 (필요시 pull)
```git clone https://github.com/yamujine/deploy-artmatch.git webhook``` webhook 폴더로 clone
* 소스 / deploy-bot 권한 설정
```chown -R www-data:www-data webroot webhook```
* delpoy-bot 호출 가능하도록 웹서버 설정
```/etc/nginx/site-enabled/pickartyou``` /webhook 호출 시 특정 PHP 호출하도록 설정
* github에 webhook 등록
https://github.com/yamujine/artmatch/settings/hooks

4. 마무리
```
service nginx restart
service mysql restart (MariaDB) 
service php7.0-fpm restart
```
