### ISSUE TITLE
기타 - 이슈 등록/처리 프로세스 정립

### ISSUE THREAD

**Issue by junho85** [yamujine/artmatch#6]
## 개요
일단 https://github.com/yamujine/artmatch/projects/1 프로젝트에서 한다. 프로젝트 세분화가 필요하면 더 만들던지 한다.
![image](https://cloud.githubusercontent.com/assets/1219373/22415347/d5d853c0-e709-11e6-8d65-f9fee48db042.png)

* TODO 우선 작업 해야 될 이슈들
* Backlog 이후 작업 해야 될 이슈들 일단 쌓아 두는 곳.
* 작업 할 땐 In Progress 로 옮겨서 작업 후 마치면 Done 으로 옮긴다.
* 이슈 담당자는 1차로 서버 - 김남우, 프론트 - 김준호, 마크업 - 이진만 으로 지정
  * 1차 담당자가 다른 분에게 이슈를 넘겨 주거나 작업을 희망하는 사람이 직접 해당 이슈를 자신을 담당자로 할당 후 작업
  * (직군에 제한은 없음)

**Comment by genie-youn** [comment]
Need review를 따로 분리하는것도 편할 것 같은데, 어떻게 생각하세요?

**Comment by junho85** [comment]
@Genie-Youn 
PR 생성하고 거기에 담당자가 지정된 경우 Need review 라는 의미로 해석 하면 될 듯 한데요.
혹시 다른 아이디어가 있으신가요?

**Comment by kimtree** [comment]
프로젝트는 단계만 보고 In Progress 상태로 놔두고, PR에서만 review 관리하면 될 것 같습니다~

**Comment by junho85** [comment]
참고로 본인에게 할당된 풀리퀘 리스트는 https://github.com/pulls/assigned 에서 볼 수 있습니다.
