### ISSUE TITLE
더보기 기능 개발

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#61]
페이징 방식이 아닌 것 같아서 1차적으로 API 개발

json으로 리턴할지, html으로 리턴할지 정의 필요

**Comment by kimtree** [comment]
@mintplo @junho85 @Nablyy 리스트 더보기 기능 관련해서 html로 된 twig를 바로 내려줄지, json으로 값만 리턴할지 프론트/마크업에서 결정해주시면 작업해서 머지하겠습니다.

**Comment by mintplo** [comment]
JSON 값으로만 받아 뷰를 다시 렌더하는건 작업도 오래걸리고 프론트에서 또 다른 템플릿 엔진을 사용해야할수도 있습니다.

일단은 서버에서 twig 자체를 렌더링해서 htmlstring으로 보내주고 그걸 추가하는게 맞지 않나 싶고 캠프할 때 렌더링 엔진을 추가 도입해서 개선하는 방향으로 가든지 하는게 어떨까요?

**Comment by mintplo** [comment]
더보기 까지 제가 하겠습니다. 로딩 인디케이터 (마크업)도 넣어야 하는 추가 이슈가 있어서요

**Comment by kimtree** [comment]
@mintplo 현재 /api/artworks /api/places API호출 가능하고, 파라미터로 q / offset / limit 쓰시면 될 것 같습니다. 해당 html view는/api/artworks.twig,  /api/places.twig 에 있습니다.
