### ISSUE TITLE
서버 - My private page 비밀번호 변경 / 프로필사진 변경 구현

### ISSUE THREAD

**Issue by genie-youn** [yamujine/artmatch#66]

**Comment by kimtree** [comment]
마이페이지 구현은 다 끝났는데 비밀번호 변경, 프로필 변경 쪽 이슈인거죠?!

**Comment by genie-youn** [comment]
네넵 비밀번호변경이랑 프로필변경이요!

**Comment by genie-youn** [comment]
비밀번호 찾기 / 페이스북 로그인은 남우님 작업중이신거 머지되고 나서 진행할께요!

**Comment by kimtree** [comment]
@Genie-Youn 머지하였으니 참고 부탁드려요~

**Comment by kimtree** [comment]
프로필사진 변경 기능 개발시
imageupload 라이브러리 참고하면 되고,
 * 기존의 사진 삭제
 * 새로운 사진 업로드 $uploaded_image_name = $this->imageupload->upload_images('profile_image', true, 'profile'); => 'profile'로 지정된 부분 꼭 이용해주세요.
