### ISSUE TITLE
회원 아이디(user_name) / 이메일(email) 중복 체크 기능 추가

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#87]
user_name은 아이디로 사용되며, /users/<user_name> 등으로 마이페이지 주소로도 쓰임

0-9 a-Z . -_ 정도 사용 가능하면 될듯함

**Comment by kimtree** [comment]
form_validation 라이브러리를 잘 활용하면 가능한데 서버쪽은 validation 추가 되어 있음.
$this->form_validation->set_rules('user_name', '유저 아이디', 'required|alpha_dash|is_unique[users.user_name]'); is_unique를 쓰면 알아서 해당 테이블의 컬럼을 찾아서 unique 여부 찾는듯.

서버에서는 해당 유저 아이디가 사용중인지 API만 만들고 프론트에서 중복체크 작업해주면 될듯

**Comment by kimtree** [comment]
/api/users/check_username?username= 

GET방식으로 중복여부 체크 가능함.

**Comment by kimtree** [comment]
/api/users/check_email?email=

이메일도 GET 방식으로 중복체크 가능한 API 만들었습니다.

**Comment by nablyy** [comment]
- [x] 회원 아이디 중복 확인
- [x] 이메일 중복 확인
- [x] 회원 아이디 형태 확인
- [x] 이메일 형태 확인

**Comment by kimtree** [comment]
아이디 - 알파벳 + . + (-_)

**Comment by nablyy** [comment]
id 정규식 . 추가
