### ISSUE TITLE
추천 키워드 기획 확인

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#98]
추천 키워드 구현시 특정 태그 검색하는 방식으로 하는 것인지, 별도 키워드용 페이지가 있는지

**Comment by thorlee** [comment]
추천 키워드는 그때 리뷰때도 말씀드렸는데, 키워드를 클릭하면 검색을 이용하게 됩니다. 별도의 페이지는 없습니다.

**Comment by kimtree** [comment]
@thorlee 검색이라면 장소의 어떤 필드를 검색해서 나오게 되어야 하는 것인가요?

**Comment by kimtree** [comment]
해당 추천 키워드는 장소와 관련되어 수동으로 입력된 "태그"에서 검색되는 것으로 결정

**Comment by kimtree** [comment]
단순 쿼리 실행하는 링크로 변경처리 https://github.com/yamujine/artmatch/commit/9c810071e3f70629b5c8b3d3b5e077def704f8c4
