### ISSUE TITLE
장소의 전시 리스트 기획 확인

### ISSUE THREAD

**Issue by kimtree** [yamujine/artmatch#99]
- 현재의 구조상 places 하위 테이블인 exhibitions 테이블에 전시 내역이 입력되어 있어야 해당 내용을 장소 상세에서 표시할 수 있음 (1:N 매핑)
- 하지만, exhibitions을 입력 받는 부분이 현재 기획되지 않음. 
    - 장소 등록시에 함께 받아서 첫번째 전시는 insert 처리를 추가할지?
    - 그냥 별도의 전시 등록 페이지가 추가 되어야 할지? (1:N 매핑이므로 여러개의 전시 추가 가능)
- 전시 정보가 등록 되어야 https://github.com/yamujine/artmatch/issues/33 전시 이력 매핑 가능함.

**Comment by thorlee** [comment]
장기적으로는 전시관리를 로그툴의 캠페인관리처럼 진행되어야 할것 같은데,
현재 버전에서는 "장소 등록시에 함께 받아서 첫번째 전시는 insert 처리를 추가할지?" 이 방법으로 일단 진행해야 할 것 같습니다.

**Comment by kimtree** [comment]
@thorlee 네, 확인하였습니다!

**Comment by kimtree** [comment]
@mintplo 장소 등록 시안이 나왔는지 모르겠는데 "A~B" 기간 입력 / 페이 여부 / 필요 작품 수 입력 UI가 있어야 하니 참고 부탁드립니다.
